### PR TITLE
Feature/banker improvements

### PR DESCRIPTION
**Pull request by enbytedev**
This pull request builds upon the changes introduced in [PR #161](https://github.com/SamB440/Tale-of-Kingdoms/pull/161) and is branched from that commit.

* Banker Improvements:
  * Percentage Button Functionality:
    * Added two sets of percentage buttons for quick transactions:
      * Player Balance: Allows players to deposit 20%, 50%, or 100% of their wallet balance directly.
      * Bank Balance: Allows players to withdraw 20%, 50%, or 100% of their bank balance directly.
  * Input Validation:
    * The banker will no longer allow negative values to be input.
* Rendering Order Fix in `ScreenContinueConquest`:
  * Fixed an issue where the background blur effect was being rendered over text. The text now renders clearly above the blurring effect.

### CODE REVIEW

**Comment by SamB440** [comment]
Needs conflicts fixing

**Comment by enbytedev** [comment]
Hey, I left a note for you in the Discord but I'm not certain it made its way to you. This has been resolved. :)

**Comment by SamB440** [comment]
It still seems to have conflicts

**Comment by SamB440** [comment]
oh, rebase and merge doesn't work with that

**Pull request merged**
